{% set version = "1.1-1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gsw
  version: {{ version.replace("-", "_") }}

source:
  fn: gsw_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/gsw_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/gsw/gsw_{{ version }}.tar.gz
  sha256: d2a21dbcc3b285163d9cf1bc649a3de1bb1e713c64e4cb6cbc3e613c43f4dd82

build:
  number: 2
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-testthat                 # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-testthat
  run:
    - r-base
    - {{ native }}gcc-libs       # [win]
    - r-testthat

test:
  commands:
    - R -e "library('gsw')"    # [not win]
    - R -e \"library('gsw')\"  # [win]

about:
  home: https://teos-10.github.io/GSW-R/index.html
  dev_url: https://github.com/TEOS-10/GSW-R
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE
  summary: Provides an interface to the Gibbs SeaWater (TEOS-10) C library, which derives from Matlab and other code written by WG127 (Working Group 127) of SCOR/IAPSO (Scientific Committee on Oceanic Research / International Association for the Physical Sciences of the Oceans).

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
