# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R-BASE=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EO0//buCsEGhLJHCyfeITrF1CJDpvtrK6lBMgU7IBFwTPWMzKslifh+3XJDn8pBwSZkqznTEeR04ZrW9DiEMJFoikKAXJqn3MnhvSXy71rH/TbcG2TTb+zTOBuw0irH1kCmh/W8/sHJi6W6vnexbQ0AXzVW9zLfRRk/pVG+e/DqbstZ+fYX51MK/aLeDlicDCpnCZvpv5rW0GqFWcydPNmoPmU+X8IivTI/2kx+fvrLu2+s0iOvwsdsX8drpPE6ORPHL4hwqD04GNePl69chcIaDOJLQxUBinCmalk3Z3kVAq7fiBaTLMAgQ2sGkAlAAkB5sKZUZcZRbZAhQLxWy+H/MhD/3nCWpjNhNxsJdFhkP4Nwc/rKS1f2/6s5/nRaMBQlw8ZQ+wrck7jls/VJdG3veyIx0vprV5DJzM9VhXj6kXiN1ZbGlH50XrOIbU0/p4ipPHqT5IZlHbXbUE2KRrLDcf5kb8d1z7NE1j22sKARjgliHK5xUpXKRbIzEwZDIANAJ77fDoWpeIdTb00R/Bnk81r4d29DfhgnykM1U4drEtEj+htQN1w9IroYjjJS6s2gWV9CcJ82KcVJcI9X0GHBqB5GUl9y/T8cZLAX8DSXXmCMkXWmoL43FQg/pfQzqULr9li0gm5ssHzfe1XP88JrngyrF2DO3QmVPoxYxon4="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
