appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WWBPsrnALsztjU9MkH3LKijsR4SJLZMLGBPk1af6jQcgbBs+zTzZN6+1+GAkpD2qZoBjNhmk8mYKapgqkspPC4JL5ba3HDCVBzVqMSpT083Qb/BCAtdPp4/HKBciVVvadQ1ISr6FJGdbttphtql5PxEsrf3wgwtHeV/9AM0lzj2LP8GjNmBYmNmpwXI0IxXYUZq1pA2ByT1PslQ8m25unGoxt9dPWGN+09LaJNy9twE3CJ5dJ9Cj8ikFE85u6XGMXUZGA1yRgb+KZIgSxmQAO0RgfP/kgzhIEb68a0OmKtRUs6R4bbJxiPr7TOXjo5ULJgLQDufJak5/lACEwOLm2uf/duSTQA9o0fiqSvR0PzQEAYJX4+U3/pETPWIyxAiHcDFzVXirxE6NxgTgL7GAxzJ2HHd7gF0jW4QZBgE7EB2qtpD3FMEUyhced8aZ/Ka4vsse8ubesGe8x0OvLAiYbOef3DgcLqyR/LihuLdZQETp3k1db1BfOy8zqaGYHBBx6x0kQy3ri1Mv+AmbpGxGuAx+FzPEoRyXIGCbfq7Ym64nmZ0kUD6QvEIKtP270eHMoPf03YODyhd8ENYHO020IMMpCf4eIVZ9xgd5Pxm7fg/ovjHymbr0lx/YOJzQb13z4X54kNfZh4sfP36gaVtQRDWJn7dU1kEX0T6Ku5tbjTI=}
